package com.learn.finance.account.api

import com.fasterxml.jackson.annotation.JsonProperty
import com.learn.finance.account.model.Account
import com.learn.finance.account.model.AccountStatus
import com.learn.finance.account.model.AccountType
import com.learn.finance.account.model.Customer
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import java.math.BigDecimal
import java.time.LocalDateTime

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * API Request/Response DTOs (Data Transfer Objects)
 *
 * KOTLIN CONCEPTS DEMONSTRATED:
 *  • data class with validation annotations
 *  • companion object factory methods (fromDomain pattern)
 *  • nullable return types
 *  • named arguments for readability
 *  • default parameter values
 * ─────────────────────────────────────────────────────────────────────────────
 */

// ── Customer Request DTOs ─────────────────────────────────────────────────────

/**
 * KOTLIN CONCEPT: data class with Jakarta validation annotations.
 * `@field:` prefix is required to target the backing field (not getter) in Kotlin.
 */
data class CreateCustomerRequest(
    @field:NotBlank(message = "First name is required")
    @JsonProperty("firstName")
    val firstName: String = "",

    @field:NotBlank(message = "Last name is required")
    @JsonProperty("lastName")
    val lastName: String = "",

    @field:NotBlank(message = "Email is required")
    @field:Email(message = "Email must be a valid address")
    @JsonProperty("email")
    val email: String = "",

    @JsonProperty("phone")
    val phone: String? = null          // nullable — phone is optional
) {
    /**
     * KOTLIN CONCEPT: extension-style function on data class.
     * Converts the request DTO into a domain model (no ID yet).
     */
    fun toDomain(): Customer = Customer(
        firstName = firstName,
        lastName  = lastName,
        email     = email,
        phone     = phone
    )
}

data class UpdateCustomerRequest(
    @field:NotBlank(message = "First name is required")
    @JsonProperty("firstName")
    val firstName: String = "",

    @field:NotBlank(message = "Last name is required")
    @JsonProperty("lastName")
    val lastName: String = "",

    @JsonProperty("phone")
    val phone: String? = null
)

// ── Customer Response DTO ─────────────────────────────────────────────────────

data class CustomerResponse(
    @JsonProperty("id")         val id: Long,
    @JsonProperty("firstName")  val firstName: String,
    @JsonProperty("lastName")   val lastName: String,
    @JsonProperty("fullName")   val fullName: String,
    @JsonProperty("email")      val email: String,
    @JsonProperty("phone")      val phone: String?,
    @JsonProperty("status")     val status: String,
    @JsonProperty("createdAt")  val createdAt: LocalDateTime?
) {
    companion object {
        /**
         * KOTLIN CONCEPT: companion object factory method.
         * The `fromDomain` pattern maps domain objects → API responses.
         * This keeps domain logic out of the API layer.
         */
        fun fromDomain(customer: Customer): CustomerResponse = CustomerResponse(
            id        = customer.id ?: error("Customer must have an ID"),
            firstName = customer.firstName,
            lastName  = customer.lastName,
            fullName  = customer.fullName,    // computed property from domain
            email     = customer.email,
            phone     = customer.phone,
            status    = customer.status,
            createdAt = customer.createdAt
        )
    }
}

// ── Account Request DTOs ──────────────────────────────────────────────────────

data class CreateAccountRequest(
    @field:NotNull(message = "Customer ID is required")
    @JsonProperty("customerId")
    val customerId: Long? = null,

    @field:NotNull(message = "Account type is required")
    @JsonProperty("accountType")
    val accountType: AccountType? = null,

    @JsonProperty("currency")
    @field:Pattern(regexp = "[A-Z]{3}", message = "Currency must be a 3-letter ISO code")
    val currency: String = "USD",

    @JsonProperty("initialDeposit")
    @field:DecimalMin(value = "0.0", message = "Initial deposit cannot be negative")
    val initialDeposit: BigDecimal = BigDecimal.ZERO
) {
    fun toDomain(): Account = Account(
        customerId    = customerId ?: error("Customer ID required"),
        accountNumber = "",             // generated by service
        accountType   = accountType ?: error("Account type required"),
        balance       = initialDeposit,
        currency      = currency
    )
}

data class UpdateAccountStatusRequest(
    @field:NotNull(message = "Status is required")
    @JsonProperty("status")
    val status: String? = null
)

// ── Account Response DTO ──────────────────────────────────────────────────────

data class AccountResponse(
    @JsonProperty("id")            val id: Long,
    @JsonProperty("customerId")    val customerId: Long,
    @JsonProperty("accountNumber") val accountNumber: String,
    @JsonProperty("accountType")   val accountType: String,
    @JsonProperty("balance")       val balance: BigDecimal,
    @JsonProperty("currency")      val currency: String,
    @JsonProperty("status")        val status: String,
    @JsonProperty("createdAt")     val createdAt: LocalDateTime?
) {
    companion object {
        fun fromDomain(account: Account): AccountResponse = AccountResponse(
            id            = account.id ?: error("Account must have an ID"),
            customerId    = account.customerId,
            accountNumber = account.accountNumber,
            accountType   = account.accountType.displayName,
            balance       = account.balance,
            currency      = account.currency,
            status        = account.status.toString(),
            createdAt     = account.createdAt
        )
    }
}

// ── Generic API Error Response ────────────────────────────────────────────────

data class ErrorResponse(
    @JsonProperty("code")    val code: Int,
    @JsonProperty("message") val message: String,
    @JsonProperty("details") val details: List<String> = emptyList()
)
